spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.25.154.202:3333/test
    username: ln
    password: ln123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true